# Generated by Django 2.0.5 on 2018-05-25 21:00

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, null=True)),
                ('method', models.CharField(max_length=10)),
                ('request_body', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('query_params', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('endpoint', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('response_body', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('response_time', models.IntegerField(null=True)),
                ('status_code', models.CharField(max_length=5, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
